name: mkg-tool
version: 0.0.1
summary: Mkg's p2p remote access tool
description: |
  ...

grade: stable
confinement: strict

apps:
#0  mkg-tool-server:
#0    command: "mkg-tool-server 2>&1 > .log" #overwrite the log 'cause i'm to lazy to rotate
#0    daemon: simple
#0    plugs:
#0      - network
#0      - network-bind
#1  mkg-tool:
#1    command: mkg-tool
#1    plugs:
#1      - network
#1      - network-bind

parts:
  tool:
    plugin: nodejs
    node-engine: 8.4.0
    source: .
#1    stage-packages:
#1      - openssh-client
