name: mkg-tool
version: 0.0.2
summary: Mkg's p2p remote access tool
description: |
  ...

grade: stable
confinement: strict

apps:
  mkg-tool-server:
    command: mkg-tool-server
    daemon: simple
    plugs:
      - network
      - network-bind

parts:
  tool:
    plugin: nodejs
    node-engine: 8.9.1
    source: .
