name: mkg-tool
version: 0.0.1
summary: Mkg's p2p remote access tool
description: |
  ...

grade: stable
confinement: strict

apps:
  mkg-tool-server:
    command: "mkg-tool-server 2>&1 > .log" #overwrite the log 'cause i'm to lazy to rotate
    daemon: simple
    plugs:
      - network
      - network-bind
#  mkg-tool:
#    command: mkg-tool
#    plugs:
#      - network
#      - network-bind
      
parts:
  tool:
    plugin: nodejs
    node-engine: 8.4.0
    source: .
